### ISSUE TITLE
Please add facelock to kivy-garden

### ISSUE THREAD

**Issue by yaki29** [kivy-garden/kivy-garden.github.io#131]
I want to add a flower named FaceLock to kivy-garden. Please add garden.facelock to kivy-garden.

**Comment by KeyWeeUsr** [comment]
I'm not sure if [this](https://github.com/yaki29/Lock-App) is the flower (you didn't provide link here), so I guess that's the thing as I don't see a similar thing in [here](https://github.com/yaki29?tab=repositories).

I have some requests, because the repo seems to be in a seriously bad state:

* [over 1000 files here](https://github.com/yaki29/Lock-App/tree/master/info), even GitHub dislikes such thing
* [over 1000 files there](https://github.com/yaki29/Lock-App/tree/master/neg)
* is [this folder](https://github.com/yaki29/Lock-App/tree/master/uglies) even necessary?
* [just no](https://github.com/yaki29/Lock-App/blob/master/download_images.py#L40), not to mention it'll fail on Py3
* [17MB video](https://github.com/yaki29/Lock-App/blob/master/video.mp4) in a repo? Why?

And basically the repo is over 33MB (imagine someone installing it). It'd be probably the best to create a new repository e.g. same-named as the flower you want to add (`garden.facelock`) and include **only** code + really necessary stuff (readme, screenshot).

If the widget _requires_ that amount of files for whatever reason (I don't believe that), it would be nice to warn the user in the readme and include only the downloader.

Anyway, any widget that depends on internet connection won't be very happy widget, unless it's explicitly a widget that **works** with internet/networking.

**Comment by yaki29** [comment]
@KeyWeeUsr Sorry for that, I wasn't aware that we are supposed to add a link to our flower as I saw some of the earlier request they didn't mention the links. 
I have made a new repository for that and removed all the clumsiness as that was just for my use.
The final link to my flower is https://github.com/yaki29/facelock

**Comment by KeyWeeUsr** [comment]
Well, I think those were just people asking for membership, but I'm kind of glad I poked more here 😋

Anyway, still some issues persist:
* it's `print()` (function), not `print ()` (tuple)
* is the [example .xml](https://github.com/yaki29/facelock/blob/3e193bfbc99726a6990b18628d10e0ea9ec7a3c8/example/haarcascade_frontalface_default.xml) the "cascade" or your face? If yes, I doubt it'll be useful as an example (obviously, not everyone has your face, so it won't unlock 😋 )
* also, please add `screenshot.png` (e.g. rename if you want), so that the [gallery](http://kivy-garden.github.io/gallery.html) works even with your flower

After that you may proceed with the transfering the repo e.g. to me and I'll put it to the garden with you ^^

**Comment by yaki29** [comment]
@KeyWeeUsr I have corrected the things that you mentioned. For the second statement, I have already taken care about that, any person with two eyes, a nose and a lip pair can unlock it :yum: . That [cascade](https://github.com/yaki29/facelock/blob/3e193bfbc99726a6990b18628d10e0ea9ec7a3c8/example/haarcascade_frontalface_default.xml) detects general frontal faces.
