### ISSUE TITLE
Garden membership and widget submission: On screen Joystick

### ISSUE THREAD

**Issue by Narcolapser** [kivy-garden/kivy-garden.github.io#135]
Discovered there was no on screen joystick. Something I need for a pair of games I'm working on. So I made one. I'd like to submit it for general use, it can be found here: https://github.com/Narcolapser/garden.joystick

However, the most recent commit there is not the one I would be submitting. I was following the steps to comply with the garden requirements, and ran into a snag:

```
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 34, in <module>
    import designer
ImportError: No module named designer

```
Not sure what to do. I'm not familiar with the designer module and there are a million other things with "designer" in there name. So I'm stuck un able to commit the changes to make it garden compliant. Any advice on what I'm missing?

**Comment by Narcolapser** [comment]
Ok, figured it out. Pulled in the wrong commit hook.

So now the repo is compliant.

**Comment by Narcolapser** [comment]
woops. hit the wrong button.

**Comment by KeyWeeUsr** [comment]
Haven't tested yet, but I like the idea. However, please change the screenshot name, so that it's `screenshot.png` (which is visible on the [garden's website](https://kivy-garden.github.io)). Later I'll test and then you might transfer the repo either to me or to someone who's online at IRC from [this group](https://kivy.org/#aboutus) with their permission/knowing that you're going to transfer.

**Comment by Narcolapser** [comment]
> screenshot.png (which is visible on the garden's website).

Then I must be blind, because I still don't see it. It just says:

> 10. As a way of self-organizing widgets, add a screenshot to your repo showcasing the widget.

Perhaps that should be updated to read something like:

> 10. As a way of self-organizing widgets, add a screenshot named screenshot.png, to your repo showcasing the widget.

Anyway. Is there any testing other than frame rate that needs to be done? Just for future reference.

**Comment by KeyWeeUsr** [comment]
Oh, I forgot to change that part. It's because of [this gallery](https://kivy-garden.github.io/gallery.html)([source](https://github.com/kivy-garden/garden/blob/master/web/generate.py)), so that when people are looking for something useful, then they can find it easier way than just looking at the code and guess what this and that actually does.

Also, the name `screenshot.png` is better than the current one even because it broke your Markdown syntax in `README.md` 😋 

I've tested it and the output looks fine (or maybe I just missed something), so feel free to come to IRC if you want to transfer the repo in real time, or just transfer it and I'll add it to garden asap when I'll be online.

Testing, well, py2+py3 support basically is the main issue and then if the widget(s) gets complex, then it's also about the framerate. I haven't really met something that exhausting though (except using `for` loops instead of `Clock` on bad places or too much (re)drawing at a single frame).

Also, what you can make better about it is to check for collisions and don't take an input from a touch that's outside of the ellipse + grab the touch, so that when I touch it with a n-th touch, the pad won't move. For example if you have a fat finger or whatever, the dev won't get wrong readings from that (or shouldn't at least).

**Comment by KeyWeeUsr** [comment]
@Narcolapser ping?

**Comment by Narcolapser** [comment]
Sorry for the delay. Was working with a reddit user on some extra features he came up with. But I think it would be sensible enough to transfer the repo to you guys now and then have him send a pull request to the garden. That sound good?

**Comment by KeyWeeUsr** [comment]
Seems fine to me :) You will be able to manage PRs on your own anyway, iirc.

**Comment by Narcolapser** [comment]
Alright then. how do I do this transfer thing?

**Comment by KeyWeeUsr** [comment]
@Narcolapser See [this](link) for more info. Feel free to come to [IRC](https://webchat.freenode.net/?nick=kvuser.&channels=kivy&uio=d4) too.

**Comment by Narcolapser** [comment]
404

**Comment by KeyWeeUsr** [comment]
Package available at https://github.com/kivy-garden/garden.joystick.
