### ISSUE TITLE
Another flower has grown.

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy-garden/kivy-garden.github.io#138]
I recently made a module named AnimationBuilder, which makes writing Kivy animations easier. If someone review this module I'd appreciate. :racehorse: 
Also correcting my English is welcome.
https://github.com/gottadiveintopython/garden.animationbuilder

**Comment by KeyWeeUsr** [comment]
Quite an interesting work. It'll be definitely useful when dealing with a lot of animations in a similar way KV handles e.g. not writing `.add_widget()` for complex layouts and so on. I can even see this as a way to create complex-ish tests for animations within Kivy itself if necessary, mainly the nesting parts.

If you want to transfer the repo to the garden, feel free to contact us at freenode#kivy-dev, then transfer the repo to someone from the core devs and we'll move it under kivy-garden. :)

Also, I'd personally appreciate a square-ish `screenshot.png` file (like in [here](https://github.com/kivy-garden/garden.mapview/blob/master/screenshot.png)) in the root of the repo which describes the best the functionality of the flower, so that it'd be visible in the [gallery](http://kivy-garden.github.io/gallery.html).

**Comment by gottadiveintopython** [comment]
Thanks for reply :)  Yep, I want to transfer the repository. You are one of the core devs, right? If so I'll transfer the repo to you after I fix some doc and screenshots/

**Comment by KeyWeeUsr** [comment]
Yes, feel free to transfer it, then ping me at #kivy-dev (though I think I've always received an email about the transfer). I tend to be active-ish there from 7-8pm CET :)

**Comment by gottadiveintopython** [comment]
Got it. Thanks always.

**Comment by KeyWeeUsr** [comment]
The repo was transfered to https://github.com/kivy-garden/garden.animationbuilder.
