### ISSUE TITLE
Please add me to Kivy Garden

### ISSUE THREAD

**Issue by GoBig87** [kivy-garden/kivy-garden.github.io#144]
Link for a merged garden PR or a proposed new flower:
<garden PR or transferable repository link>
Hey for my kivy app I had to find a way to integrate stripe into android and ios.  I've started a repo here (https://github.com/GoBig87/Stripe) with all of the code that is needed to implement stripe along with a demo app and demo server to help get users started.  The demo app and demo server need a little polishing still but the underlying stripe has been working for me.

**Comment by matham** [comment]
Can you please structure the flower in the new format as described [here](https://kivy-garden.github.io/index.html#developmentguidelines) and then request again? The old garden tool is being deprecated in favor of the new package structure so that it can be installed like any normal Python package without needing custom garden installers. With the new package format, it can be added to setup.py like any normal dependency.
