### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by olivier-boesch** [kivy-garden/kivy-garden.github.io#145]
Link for a merged garden PR or a proposed new flower:
a led widget with default shapes : https://github.com/olivier-boesch/garden.led

**Comment by olivier-boesch** [comment]
Documentation was added. let me know how to add it to the garden.

Thanks.

**Comment by matham** [comment]
Can you please structure the flower in the new format as described [here](https://kivy-garden.github.io/index.html#developmentguidelines) and then request again? The old garden tool is being deprecated in favor of the new package structure so that it can be installed like any normal Python package without needing custom garden installers. With the new package format, it can be added to setup.py like any normal dependency.
