### ISSUE TITLE
an image toggle button widget

### ISSUE THREAD

**Issue by olivier-boesch** [kivy-garden/kivy-garden.github.io#146]
Link for a merged garden PR or a proposed new flower:
https://github.com/olivier-boesch/garden.imagetogglebutton

This is an image toggle button (as we can see in kivy's doc) with several feature. source and/or color change with state...

features in common with garden.led : https://github.com/olivier-boesch/garden.led

let me know if this can be added to garden.
Olivier.

**Comment by matham** [comment]
Can you please structure the flower in the new format as described [here](https://kivy-garden.github.io/index.html#developmentguidelines) and then request again? The old garden tool is being deprecated in favor of the new package structure so that it can be installed like any normal Python package without needing custom garden installers. With the new package format, it can be added to setup.py like any normal dependency.
